name: invobharat
description: A cross-platform invoice generator for India.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.0
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  google_fonts: ^7.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.2.1
  open_file: ^3.3.2
  uuid: ^4.5.2
  fluent_ui: ^4.12.0
  file_picker: ^10.3.8

  archive: ^4.0.7
  url_launcher: ^6.3.2
  libadwaita: ^2.0.2

  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  image: ^4.7.2
  xml: ^6.6.1
  petitparser: ^7.0.1
  analyzer: ^9.0.0
  characters: ^1.4.1
  matcher: ^0.12.18
  material_color_utilities: ^0.13.0
  math_expressions: ^3.1.0
  test: ^1.28.0
  test_api: ^0.7.8
  test_core: ^0.6.14

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "logo.png"
  windows:
    generate: true
    icon_size: 48
  linux: true

flutter:
  uses-material-design: true
  assets: 
    - logo.png

