name: invobharat
description: A cross-platform invoice generator for India.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.0
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  google_fonts: ^7.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.2.1
  uuid: ^4.5.2
  fluent_ui: ^4.12.0
  file_picker: ^10.3.8
  fl_chart: ^0.66.0

  # Database
  drift: ^2.14.0
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.18
  path: ^1.9.0

  archive: ^4.0.7
  url_launcher: ^6.3.2

  qr_flutter: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  drift_dev: ^2.14.0



flutter_launcher_icons:
  android: false
  ios: false
  image_path: "logo.png"
  windows:
    generate: true
    icon_size: 48
  linux: true

flutter:
  uses-material-design: true
  assets: 
    - logo.png

