name: invobharat
description: A cross-platform invoice generator for India.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.0
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.2.1
  open_file: ^3.3.2
  uuid: ^4.5.2
  fluent_ui: ^4.12.0
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "logo.png"
  windows:
    generate: true
    icon_size: 48

flutter:
  uses-material-design: true
  assets: []  # Ensures AssetManifest is generated
