name: invobharat
description: A cross-platform invoice generator for India.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.0
  intl: ^0.19.0
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "logo.png"
  windows:
    generate: true
    icon_size: 48

flutter:
  uses-material-design: true
